# Generated by Django 3.0.5 on 2021-02-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.TextField(),
        ),
    ]
