# Generated by Django 3.0.5 on 2021-03-29 13:29

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210329_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.jpg', upload_to=category.models.upload_to, verbose_name='Image'),
        ),
    ]
