export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'


export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'


export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS'
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL'


export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'


export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'


export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL'
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS'


export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL'
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS'


export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS'
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL'
export const LOGOUT = 'LOGOUT'


export const GET_PRODUCT = 'GET_PRODUCT'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS'
export const PRODUCT_DETAILS_ERROR = 'PRODUCT_DETAILS_ERROR'


export const GET_CATEGORY = 'GET_CATEGORY'
export const CATEGORY_ERROR = 'CATEGORY_ERROR'


export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const SEARCH_PRODUCT_ERROR = 'SEARCH_PRODUCT_ERROR'

export const COMPARE_PRODUCT = 'COMPARE_PRODUCT'
export const COMPARE_PRODUCT_ERROR = 'COMPARE_PRODUCT_ERROR'


export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY'
export const SUB_CATEGORY_ERROR = 'SUB_CATEGORY_ERROR'


export const TOP_PROMOTION = 'TOP_PROMOTION'
export const TOP_PROMOTION_ERROR = 'TOP_PROMOTION_ERROR'


export const GET_PRODUCT_BY_CATEGORY = 'GET_PRODUCT_BY_CATEGORY'
export const GET_PRODUCT_BY_CATEGORY_ERROR = 'GET_PRODUCT_BY_CATEGORY_ERROR'

export const WISHLIST_ADDED = 'WISHLIST_ADDED'
export const WISHLIST_ADDED_ERROR = 'WISHLIST_ADDED_ERROR'

export const CONTACT_SUCCESS = 'CONTACT_SUCCESS'
export const CONTACT_FAIL = 'CONTACT_FAIL'

export const BRAND_DELETE_REQUEST = 'BRAND_DELETE_REQUEST'
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS'
export const BRAND_DELETE_FAIL = 'BRAND_DELETE_FAIL'
