# Generated by Django 3.2.3 on 2021-06-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210531_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ip',
        ),
    ]
