# Generated by Django 3.0.5 on 2021-03-16 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_auto_20210316_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='admin', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('favorite_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator_favorite', to=settings.AUTH_USER_MODEL)),
                ('product_favorites', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'Favorites',
            },
        ),
    ]
