# Generated by Django 3.0.5 on 2021-03-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='author',
        ),
    ]
