# Generated by Django 3.2.3 on 2021-05-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
    ]
