# Generated by Django 3.2.3 on 2021-06-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210603_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='ordered',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='session_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
