# Generated by Django 3.0.5 on 2021-04-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_users_wishlist'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='products_wishlist',
            field=models.ManyToManyField(blank=True, related_name='products_wishlist', to='products.Product'),
        ),
    ]
