# Generated by Django 3.0.5 on 2021-05-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_users_wishlist'),
        ('account', '0002_account_products_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='products_wishlist',
        ),
        migrations.AddField(
            model_name='account',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='users_wishlist', to='products.Product'),
        ),
    ]
