# Generated by Django 3.2.3 on 2021-05-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210513_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='users_wishlist',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
