# Generated by Django 3.0.5 on 2021-05-26 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210525_2305'),
        ('post', '0004_auto_20210524_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
